-- 자동 생성: cat-db/scripts/build_tag_seed.py tags-v0.2.yaml — 직접 고치지 말 것
BEGIN;
INSERT INTO cat.tags (dimension, code, label, layer, deprecated, taxonomy_version) VALUES
  ('grade', 'g8_below', '8학년 이하', 'AB', false, '0.2'),
  ('grade', 'g9', '9학년', 'AB', false, '0.2'),
  ('grade', 'g10', '10학년', 'AB', false, '0.2'),
  ('grade', 'g11', '11학년', 'AB', false, '0.2'),
  ('grade', 'g12', '12학년', 'AB', false, '0.2'),
  ('grade', 'transfer', '편입', 'AB', false, '0.2'),
  ('major', 'cs', '컴퓨터과학·AI', 'AB', false, '0.2'),
  ('major', 'engineering', '공학', 'AB', false, '0.2'),
  ('major', 'bio_premed', '생명과학·프리메드', 'AB', false, '0.2'),
  ('major', 'med_dental', '의·치대', 'AB', false, '0.2'),
  ('major', 'public_health', '보건', 'AB', false, '0.2'),
  ('major', 'physical_sci', '물리·화학·수학', 'AB', false, '0.2'),
  ('major', 'business', '경영·경제', 'AB', false, '0.2'),
  ('major', 'social_sci', '사회과학·법·정치', 'AB', false, '0.2'),
  ('major', 'psychology', '심리', 'AB', false, '0.2'),
  ('major', 'humanities', '인문', 'AB', false, '0.2'),
  ('major', 'arts', '예술·미디어·건축', 'AB', false, '0.2'),
  ('major', 'interdisciplinary', '다학제·융합', 'AB', false, '0.2'),
  ('major', 'undecided', '미정', 'AB', false, '0.2'),
  ('school_level', 'undergrad_us', '미국 학부', 'AB', false, '0.2'),
  ('school_level', 'undergrad_uk', '영국 학부', 'AB', false, '0.2'),
  ('school_level', 'boarding', '보딩스쿨', 'AB', false, '0.2'),
  ('school_level', 'grad_med', '의대·대학원', 'AB', false, '0.2'),
  ('project_type', 'research', '리서치·논문', 'AB', false, '0.2'),
  ('project_type', 'competition', '대회·올림피아드', 'AB', false, '0.2'),
  ('project_type', 'summer_program', '여름 프로그램', 'AB', false, '0.2'),
  ('project_type', 'internship', '인턴십', 'AB', false, '0.2'),
  ('project_type', 'passion_project', '열정 프로젝트·제작', 'AB', false, '0.2'),
  ('project_type', 'social_impact', '봉사·소셜임팩트·비영리', 'AB', false, '0.2'),
  ('project_type', 'leadership', '리더십·동아리 창립', 'AB', false, '0.2'),
  ('project_type', 'capstone', '캡스톤·전공조합', 'AB', false, '0.2'),
  ('project_type', 'essay_competition', '에세이 대회', 'AB', false, '0.2'),
  ('project_type', 'arts_portfolio', '예술 포트폴리오', 'AB', false, '0.2'),
  ('project_type', 'athletics', '운동', 'AB', false, '0.2'),
  ('project_type', 'online_course', '온라인 코스', 'AB', false, '0.2'),
  ('project_type', 'media_journalism', '기자단·학교 신문·미디어', 'AB', false, '0.2'),
  ('project_type', 'mentoring', '또래 상담·튜터링·멘토링', 'AB', false, '0.2'),
  ('topic', 'academics', '학업(GPA·과목 선택)', 'AB', false, '0.2'),
  ('topic', 'testing', '시험(SAT·AP·영어)', 'AB', false, '0.2'),
  ('topic', 'ec', '비교과(EC)', 'AB', false, '0.2'),
  ('topic', 'essay', '에세이', 'AB', false, '0.2'),
  ('topic', 'application', '원서 작성(액티비티·추가정보)', 'AB', false, '0.2'),
  ('topic', 'recommendation', '추천서', 'AB', false, '0.2'),
  ('topic', 'early_round', '조기전형', 'AB', false, '0.2'),
  ('topic', 'financial_aid', '재정보조·장학', 'AB', false, '0.2'),
  ('topic', 'interview', '인터뷰', 'AB', false, '0.2'),
  ('topic', 'school_selection', '학교 선정', 'AB', false, '0.2'),
  ('doc_type', 'school_guide', '학교별 합격가이드', 'A', false, '0.2'),
  ('doc_type', 'admit_case', '합격 사례 프로필', 'A', false, '0.2'),
  ('doc_type', 'data_analysis', 'CDS·소송기록 등 데이터 분석', 'A', false, '0.2'),
  ('doc_type', 'policy_table', '시험·전형 정책표', 'A', false, '0.2'),
  ('doc_type', 'timeline', '학년별 캘린더·체크리스트', 'A', false, '0.2'),
  ('doc_type', 'opportunity_list', 'EC·대회·프로그램 리스트', 'A', false, '0.2'),
  ('doc_type', 'strategy_guide', '전략 가이드', 'A', false, '0.2'),
  ('doc_type', 'major_track', '전공 트랙', 'A', false, '0.2'),
  ('doc_type', 'webinar', '웨비나(녹음·요약)', 'A', false, '0.2'),
  ('doc_type', 'sns_video', '인스타·SNS 영상', 'A', false, '0.2'),
  ('audience', 'parent', '학부모', 'A', false, '0.2'),
  ('audience', 'student', '학생', 'A', false, '0.2'),
  ('audience', 'internal', '내부(컨설턴트)', 'A', false, '0.2'),
  ('strength', 'coherent_narrative', '활동이 한 문장/한 관심사로 꿰임', 'B', false, '0.2'),
  ('strength', 'major_aligned_awards', '전공과 결이 맞는 수상', 'B', false, '0.2'),
  ('strength', 'measurable_impact', '대상·산출물·측정된 변화가 있음', 'B', false, '0.2'),
  ('strength', 'external_validation', '외부 검증(게재·입상·채택)', 'B', false, '0.2'),
  ('strength', 'initiative', '자기주도(콜드메일·창립·제안)', 'B', false, '0.2'),
  ('strength', 'rigor', '도전적 과목 선택', 'B', false, '0.2'),
  ('strength', 'depth_over_breadth', '깊이 있는 소수 트랙', 'B', false, '0.2'),
  ('strength', 'gap_explained', '공백·어려움을 소명하고 재료로 씀', 'B', false, '0.2'),
  ('issue', 'scattered_activities', '활동 산만·방향 없음', 'B', false, '0.2'),
  ('issue', 'no_target_audience', '대상(누구에게) 불명확', 'B', false, '0.2'),
  ('issue', 'no_baseline', '기준선(Before) 측정 없음', 'B', false, '0.2'),
  ('issue', 'no_output', '남는 산출물 없음', 'B', false, '0.2'),
  ('issue', 'title_only_leadership', '직함만 있는 리더십', 'B', false, '0.2'),
  ('issue', 'late_start', '착수 시기 늦음', 'B', false, '0.2'),
  ('issue', 'unrelated_awards', '전공과 무관한 수상 나열', 'B', false, '0.2'),
  ('issue', 'us_uk_mismatch', '미국/영국 트랙 혼선', 'B', false, '0.2'),
  ('issue', 'weak_rigor', '과목 난이도 부족', 'B', false, '0.2'),
  ('activity_status', 'proposed', '제안됨', 'B', false, '0.2'),
  ('activity_status', 'planned', '하기로 함', 'B', false, '0.2'),
  ('activity_status', 'ongoing', '진행 중', 'B', false, '0.2'),
  ('activity_status', 'completed', '완료', 'B', false, '0.2'),
  ('activity_status', 'on_hold', '보류', 'B', false, '0.2'),
  ('activity_status', 'dropped', '중단·제외', 'B', false, '0.2'),
  ('student_issue', 'undecided_major', '전공 미정·방향 탐색 중', 'B', false, '0.2'),
  ('student_issue', 'test_score_gap', '시험 점수와 목표 격차 큼', 'B', false, '0.2'),
  ('student_issue', 'activity_interest_mismatch', '활동 구성과 실제 관심 불일치', 'B', false, '0.2'),
  ('student_issue', 'low_engagement', '제안 활동에 흥미 낮음', 'B', false, '0.2'),
  ('student_issue', 'procrastination', '미루는 습관·루틴 부재', 'B', false, '0.2'),
  ('student_issue', 'writing_confidence', '글쓰기 자신감 부족', 'B', false, '0.2'),
  ('student_issue', 'portfolio_deadline_risk', '포트폴리오 준비 시한 위험', 'B', false, '0.2'),
  ('student_issue', 'time_constraint', '시간 부족·우선순위 조정 필요', 'B', false, '0.2'),
  ('student_issue', 'health_injury', '부상·건강 제약', 'B', false, '0.2'),
  ('student_issue', 'late_start', '준비 착수 늦음', 'B', false, '0.2'),
  ('strength_theme', 'relator', '절친', 'B', false, '0.2'),
  ('strength_theme', 'adaptability', '적응', 'B', false, '0.2'),
  ('strength_theme', 'harmony', '화합', 'B', false, '0.2'),
  ('strength_theme', 'developer', '개발', 'B', false, '0.2'),
  ('strength_theme', 'ideation', '발상', 'B', false, '0.2'),
  ('strength_theme', 'strategic', '전략', 'B', false, '0.2'),
  ('strength_theme', 'achiever', '성취', 'B', false, '0.2'),
  ('strength_theme', 'learner', '배움', 'B', false, '0.2'),
  ('strength_theme', 'empathy', '공감', 'B', false, '0.2'),
  ('strength_theme', 'responsibility', '책임', 'B', false, '0.2')
ON CONFLICT (dimension, code) DO UPDATE SET label = EXCLUDED.label, layer = EXCLUDED.layer,
  deprecated = EXCLUDED.deprecated, taxonomy_version = EXCLUDED.taxonomy_version;
UPDATE cat.tags SET deprecated = true WHERE taxonomy_version <> '0.2';
COMMIT;
